/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicListRouteImport } from './routes/(public)/list'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicListRoute = publicListRouteImport.update({
  id: '/(public)/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/list': typeof publicListRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesByTo {
  '/list': typeof publicListRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/list': typeof publicListRoute
  '/(public)/': typeof publicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/list' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/list' | '/'
  id: '__root__' | '/(public)/list' | '/(public)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicListRoute: typeof publicListRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/list': {
      id: '/(public)/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof publicListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicListRoute: publicListRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
